### ISSUE TITLE
Proper Vendor Prefixed Namespacing

### ISSUE THREAD

**Issue by renzo-s** [voku/Stringy#19]
I'm running into issues `Ambiguous class resolution` warnings from composer since some require your fork and others the older unmaintained version. I could ask there to vendor prefix the lib, but well, it's dead. I do understand the backward compat issues with this though...

**Comment by voku** [comment]
Did something like this ...

```json
"replace": {
    "danielstjules/stringy": "~3.0"
  },
```

... solve the problem? Shoud I add it into the composer.json from this fork?

**Comment by GrahamCampbell** [comment]
Hmm, replace is wrong, because it will allow composer to install this package in place of stringy v3, meaning the user will get v5, which may break their code. Maybe it should have been "conflict", but it's kinda too late to add that, since composer will just resolve a version of this package before the conflict data was added in order to get a version that doesn't say it conflicts.

**Comment by cliffordp** [comment]
@renzo-s, consider using one of these:

- https://github.com/TypistTech/imposter-plugin --> https://typist.tech/portfolio-item/imposter/
- https://deliciousbrains.com/php-scoper-namespace-composer-depencies/ --> https://github.com/humbug/php-scoper
- https://github.com/coenjacobs/mozart
